Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DocumentLibraryManagementSystem.Controllers
{
    public class AjaxController : Controller
    {

        DLMSDatabaseEntities context = new DLMSDatabaseEntities();
        // GET: Ajax
        public JsonResult District(int Sid)
        {

            var result = context.District.Where(x => x.State_Id == Sid).ToList();

            var selectList = new SelectList(result, "Id", "Name")
;
            return Json(selectList, JsonRequestBehavior.AllowGet);

        }

        public JsonResult Palika(int Pid)
        {

            var result = context.Palika.Where(x => x.District_Id == Pid).ToList();

            var selectList = new SelectList(result, "Id", "Name")
;
            return Json(selectList, JsonRequestBehavior.AllowGet);

        }

        public JsonResult SubCategoryAjax(int Scid)
        {

            var result = context.Sub_Category.Where(x => x.Category_Id == Scid).ToList();

            var selectList = new SelectList(result, "Id", "Name")
;
            return Json(selectList, JsonRequestBehavior.AllowGet);

        }
        //public SelectList District(int Sid)
        //{
        //    using (var context = new DLMSDatabaseEntities())
        //    {
        //        var result = context.District.Where(x => x.State_Id == Sid).ToList();


        //        return new SelectList(result, "Id", "Name");
        //    }
        //}
    }
}

Controllers/DocumentController.cs
using DocumentLibraryManagementSystem.DbOperations;
using DocumentLibraryManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DocumentLibraryManagementSystem.Controllers
{
    public class DocumentController : Controller
    {
        DocumentRepository repository = null;

        public DocumentController()
        {
            repository = new DocumentRepository();

        }
        // GET: Category
        public ActionResult Create()
        {
            using (var con = new DLMSDatabaseEntities())
            {
                ViewBag.CategoryList = new SelectList(con.Category.ToList(), "Id", "Name");
                ViewBag.SubCategoryList = new SelectList(con.Sub_Category.ToList(), "Id", "Name");
                ViewBag.DocumentSource = new SelectList(con.Document_Source.ToList(), "Id", "Name");
                ViewBag.FiscalYear = new SelectList(con.Fiscal_Year.ToList(), "Id", "Name");
                ViewBag.StateList = new SelectList(con.State.ToList(), "Id", "Name");
                ViewBag.DistrictList = new SelectList(con.District.ToList(), "Id", "Name");
                ViewBag.PalikaList = new SelectList(con.Palika.ToList(), "Id", "Name");
                ViewBag.DocumentType = new SelectList(con.Document_Type.ToList(), "Id", "Name");



            }
            return View();
        }

        [HttpPost]
        public ActionResult Create(DocumentModel model)
        {
            if (ModelState.IsValid)
            {
                int id = repository.AddDocument(model);
                if (id > 0)
                {
                    ModelState.Clear();
                    ViewBag.IsSuccess = "Data Added";
                }
            }
            return RedirectToAction("GetAllRecords");
        }

        public ActionResult GetAllRecords()
        {
            var result = repository.GetAllDocuments();
            return View(result);
        }

        public ActionResult Details(int id)
        {
            var doc = repository.GetDocument(id);
            return View(doc);
        }

        public ActionResult Edit(int id)
        {
            using (var con = new DLMSDatabaseEntities())
            {
                ViewBag.CategoryList = new SelectList(con.Category.ToList(), "Id", "Name");
                ViewBag.SubCategoryList = new SelectList(con.Sub_Category.ToList(), "Id", "Name");
                ViewBag.DocumentSource = new SelectList(con.Document_Source.ToList(), "Id", "Name");
                ViewBag.FiscalYear = new SelectList(con.Fiscal_Year.ToList(), "Id", "Name");
                ViewBag.StateList = new SelectList(con.State.ToList(), "Id", "Name");
                ViewBag.DistrictList = new SelectList(con.District.ToList(), "Id", "Name");
                ViewBag.PalikaList = new SelectList(con.Palika.ToList(), "Id", "Name");
                ViewBag.DocumentType = new SelectList(con.Document_Type.ToList(), "Id", "Name");


            }
            var doc = repository.GetDocument(id);
            return View(doc);
        }


        [HttpPost]
        public ActionResult Edit(DocumentModel model)
        {
            if (ModelState.IsValid)
            {
                repository.UpdateDocument(model.Id, model);

                return RedirectToAction("GetAllRecords");
            }
            return View();

        }


        public ActionResult Delete(int id)
        {
            repository.DeleteDocument(id);
            return RedirectToAction("GetAllRecords");
        }

        [HttpPost]
        public ActionResult Upload(DocumentFileModel model)
        {

            var imagePath = "/File/";

            using (var con = new DLMSDatabaseEntities())
            {
                if (model.ImageFile != null)
                {


                    var fileName = Path.GetFileName(model.ImageFile.FileName);
                    var path = Path.Combine(Server.MapPath(imagePath), fileName);
                    model.ImageFile.SaveAs(path);
                    model.File_Path = imagePath + model.ImageFile.FileName;
                    Document_File document_File = new Document_File()
                    {
                        File_Path = model.File_Path,
                        Name = fileName,
                    };
                    con.Document_File.Add(document_File);
                    con.SaveChanges();



                }

            }



            return View();
        }

        //public ActionResult GetCountry()
        //{
        //    List<State> Statelist = db.State.ToList();
        //    ViewBag.StateList = new SelectList(Statelist, "Id", "Name");
        //    return View();
        //}




    }
}

Views/Document/Create.cshtml
@model DocumentLibraryManagementSystem.Models.DocumentModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>DocumentModel</h4>
    <h3>@ViewBag.IsSuccess</h3>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Category_Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Category_Id, ViewBag.CategoryList as SelectList, "Select Category", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Category_Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Sub_Category_Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Sub_Category_Id, ViewBag.SubCategoryList as SelectList, "Select SubCategory ", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Sub_Category_Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Document_Source_Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Document_Source_Id, ViewBag.DocumentSource as SelectList, "Select Document Source ", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Document_Source_Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Fiscal_Year_Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Fiscal_Year_Id, ViewBag.FiscalYear as SelectList, "Select Fiscal Year", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Fiscal_Year_Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.State_Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @if (ViewBag.StateList != null)
            {
                @Html.DropDownListFor(model => model.State_Id, ViewBag.StateList as SelectList, "Select State", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.State_Id, "", new { @class = "text-danger" })

            }

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.District_Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.District_Id, ViewBag.DistrictList as SelectList, "Select District", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.District_Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Palika_Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Palika_Id, ViewBag.PalikaList as SelectList, "Select Palika", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Palika_Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Document_Type_Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Document_Type_Id, ViewBag.DocumentType as SelectList, "Select Document Type", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Document_Type_Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.ImageFile, new { type = "file" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Home")
</div>
@section Scripts{

    <script>
        $(document).ready(function () {
            $("#State_Id").change(function () {
                var selectedCountryId = $(this).val();
                $.ajax({
                    url: "@Url.Action("District", "Ajax")",
                    type: "GET",
                    data: { Sid: selectedCountryId },
                    success: function (data) {
                        $("#District_Id").empty();
                        $("#District_Id").append('<option value="">Select District</option>');
                        $.each(data, function (index, district) {
                            $("#District_Id").append('<option value="' + district.Value + '">' + district.Text + '</option>');
                        });
                    }
                });


            });
            $("#District_Id").change(function () {
                var selectedDistrictId = $(this).val();
                $.ajax({
                    url: "@Url.Action("Palika", "Ajax")",
                    type: "GET",
                    data: { Pid: selectedDistrictId },
                    success: function (data) {
                        $("#Palika_Id").empty();
                        $("#Palika_Id").append('<option value="">Select Palika</option>');
                        $.each(data, function (index, palika) {
                            $("#Palika_Id").append('<option value="' + palika.Value + '">' + palika.Text + '</option>');
                        });
                    }

                });
            });

            $("#Category_Id").change(function () {
                var selectedCategoryId = $(this).val();
                $.ajax({
                    url: "@Url.Action("SubCategoryAjax", "Ajax")",
                    type: "GET",
                    data: { Scid: selectedCategoryId },
                    success: function (data) {
                        $("#Sub_Category_Id").empty();
                        $("#Sub_Category_Id").append('<option value="">Select Sub_Category</option>');
                        $.each(data, function (index, subcategory) {
                            $("#Sub_Category_Id").append('<option value="' + subcategory.Value + '">' + subcategory.Text + '</option>');
                        });
                    }

                });
            });

        });



    </script>


}

Views/Document/Details.cshtml
@model DocumentLibraryManagementSystem.Models.DocumentModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>DocumentModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sub_Category_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sub_Category_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Document_Source_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Document_Source_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fiscal_Year_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fiscal_Year_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.District_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.District_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Palika_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Palika_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Document_Type_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Document_Type_Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Document/Edit.cshtml
@model DocumentLibraryManagementSystem.Models.DocumentModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DocumentModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Category_Id, ViewBag.CategoryList as SelectList, "Select Category", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Category_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sub_Category_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Sub_Category_Id, ViewBag.SubCategoryList as SelectList, "Select SubCategory", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Sub_Category_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Document_Source_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Document_Source_Id, ViewBag.DocumentSource as SelectList, "Select Document Source", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Document_Source_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fiscal_Year_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Fiscal_Year_Id, ViewBag.FiscalYear as SelectList, "Select Fiscal Year", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Fiscal_Year_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.State_Id, ViewBag.StateList as SelectList, "Select State", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.State_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.District_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.District_Id, ViewBag.DistrictList as SelectList, "Select District", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.District_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Palika_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Palika_Id, ViewBag.PalikaList as SelectList, "Select Palika", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Palika_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Document_Type_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Document_Type_Id, ViewBag.DocumentType as SelectList, "Select Document Type", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Document_Type_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Document/GetAllRecords.cshtml
@model IEnumerable<DocumentLibraryManagementSystem.Models.DocumentModel>

@{
    ViewBag.Title = "GetAllRecords";
}

<h2>GetAllRecords</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table id="example" class="table table-striped" style="width:100%">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sub_Category_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Document_Source_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fiscal_Year_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.District_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Palika_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Document_Type_Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sub_Category_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Document_Source_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fiscal_Year_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.District_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Palika_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Document_Type_Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>